# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(357, 413)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lable = QtWidgets.QLabel(parent=self.centralwidget)
        self.lable.setGeometry(QtCore.QRect(60, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lable.setFont(font)
        self.lable.setMouseTracking(False)
        self.lable.setObjectName("lable")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 357, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(parent=self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menusetting = QtWidgets.QMenu(parent=self.menuEdit)
        self.menusetting.setObjectName("menusetting")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionnew = QtGui.QAction(parent=MainWindow)
        self.actionnew.setObjectName("actionnew")
        self.actionsave_as_a_new_one = QtGui.QAction(parent=MainWindow)
        self.actionsave_as_a_new_one.setObjectName("actionsave_as_a_new_one")
        self.actionopen = QtGui.QAction(parent=MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtGui.QAction(parent=MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionfont_size = QtGui.QAction(parent=MainWindow)
        self.actionfont_size.setObjectName("actionfont_size")
        self.menufile.addAction(self.actionnew)
        self.menufile.addAction(self.actionsave)
        self.menusetting.addAction(self.actionfont_size)
        self.menuEdit.addAction(self.menusetting.menuAction())
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        self.actionfont_size.triggered.connect(lambda: self.clicked("font   size is clicked"))
        self.actionsave.triggered.connect(lambda: self.clicked("save is clicked"))
        self.actionnew.triggered.connect(lambda: self.clicked("new is clicked"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MyWindow"))
        self.lable.setText(_translate("MainWindow", "lable"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menusetting.setTitle(_translate("MainWindow", "setting"))
        self.actionnew.setText(_translate("MainWindow", "new"))
        self.actionnew.setStatusTip(_translate("MainWindow", "creat a new file"))
        self.actionnew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionsave_as_a_new_one.setText(_translate("MainWindow", "save as a new one"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionsave.setStatusTip(_translate("MainWindow", "saveing file"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionfont_size.setText(_translate("MainWindow", "font size"))
        self.actionfont_size.setShortcut(_translate("MainWindow", "ESC"))
        
    def clicked(self, text="something clicked"):
        self.lable.setText(text)
        self.lable.adjustSize()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
